[package]
name = "mysimpledecoder"
version = "0.1.0"
edition = "2024"

[dependencies]

[lints]
workspace = true
[build-dependencies]
cc = { version = "1.0", features = ["parallel"] }
walkdir = "2.3"
nasm-rs = "0.3.0"
